- name: tear down existing OSD filesystems then logical volumes, volume groups, and physical volumes
  hosts:
  - osds

  tasks:
  - name: include vars of lv_vars.yaml
    include_vars:
      file: lv_vars.yaml

  # need to check if lvm2 is installed
  - name: install lvm2
    package:
      name: lvm2
      state: present

# BEGIN TEARDOWN
  - name: find any existing OSD filesystems
    shell: "grep /var/lib/ceph/osd /proc/mounts | awk '{print $2}'"
    register: old_osd_filesystems

  - name: tear down any existing OSD filesystems
    shell: "umount -v {{item}}"
    with_items: "{{old_osd_filesystems.stdout_lines}}"

  - name: kill all LVM commands that may have been hung
    shell: "killall -q lvcreate pvcreate vgcreate lvconvert || echo -n"
    failed_when: false

  ## Logcal Vols
  - name: tear down any existing ceph named LVM logical volumes
    lvol:
      lv: "{{item.name}}"
      vg: "{{vg_name}}"
      state: absent
      force: yes
    with_items:
      - "{{ lvs }}"

  ## Volume Groups
  - name: Remove VG
    lvg:
      vg: "{{vg_name}}"
      state: absent

  ## Physical Vols
  - name: tear down PV for device
    shell: "pvremove --force --yes {{device}}"
